package com.quinn.util.constant;

import java.util.HashMap;
import java.util.Map;

/**
 * MIME类型
 *
 * @author Qunhua.Liao
 * @since 2020-04-05
 */
public final class MimeMapper {

    /**
     * 默认文件类型：未定义
     */
    public static final String DEFAULT_FILE_TYPE = "undef";

    /**
     * 默认类型
     */
    public static final String DEFAULT_MIME_TYPE = "application/octet-stream";

    public static final Map<String, String> MIME_MAP = new HashMap<>();

    static {
        MIME_MAP.put("docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document");
        MIME_MAP.put("xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
        MIME_MAP.put("pptx", "application/vnd.openxmlformats-officedocument.presentationml.presentation");
        MIME_MAP.put("ppsx", "application/vnd.openxmlformats-officedocument.presentationml.slideshow");
        MIME_MAP.put("mdbx", "application/msaccess");
        MIME_MAP.put("001    ".trim(), "application/x-001                          ".trim());
        MIME_MAP.put("301    ".trim(), "application/x-301                   ".trim());
        MIME_MAP.put("323    ".trim(), "text/h323                                  ".trim());
        MIME_MAP.put("906    ".trim(), "application/x-906                   ".trim());
        MIME_MAP.put("907    ".trim(), "drawing/907                                  ".trim());
        MIME_MAP.put("a11    ".trim(), "application/x-a11                   ".trim());
        MIME_MAP.put("acp    ".trim(), "audio/x-mei-aac                              ".trim());
        MIME_MAP.put("ai    ".trim(), "application/postscript              ".trim());
        MIME_MAP.put("aif    ".trim(), "audio/aiff                                  ".trim());
        MIME_MAP.put("aifc".trim(), "audio/aiff                          ".trim());
        MIME_MAP.put("aiff    ".trim(), "audio/aiff                                  ".trim());
        MIME_MAP.put("anv    ".trim(), "application/x-anv                   ".trim());
        MIME_MAP.put("asa    ".trim(), "text/asa                                      ".trim());
        MIME_MAP.put("asf    ".trim(), "video/x-ms-asf                      ".trim());
        MIME_MAP.put("asp    ".trim(), "text/asp                                      ".trim());
        MIME_MAP.put("asx    ".trim(), "video/x-ms-asf                      ".trim());
        MIME_MAP.put("au        ".trim(), "audio/basic                                  ".trim());
        MIME_MAP.put("avi    ".trim(), "video/avi                           ".trim());
        MIME_MAP.put("awf    ".trim(), "application/vnd.adobe.workflow              ".trim());
        MIME_MAP.put("biz    ".trim(), "text/xml                            ".trim());
        MIME_MAP.put("bmp    ".trim(), "application/x-bmp                          ".trim());
        MIME_MAP.put("bot    ".trim(), "application/x-bot                   ".trim());
        MIME_MAP.put("c4t    ".trim(), "application/x-c4t                          ".trim());
        MIME_MAP.put("c90    ".trim(), "application/x-c90                   ".trim());
        MIME_MAP.put("cal    ".trim(), "application/x-cals                          ".trim());
        MIME_MAP.put("cat    ".trim(), "application/vnd.ms-pki.seccat       ".trim());
        MIME_MAP.put("cdf    ".trim(), "application/x-netcdf                          ".trim());
        MIME_MAP.put("cdr    ".trim(), "application/x-cdr                   ".trim());
        MIME_MAP.put("cel    ".trim(), "application/x-cel                          ".trim());
        MIME_MAP.put("cer    ".trim(), "application/x-x509-ca-cert          ".trim());
        MIME_MAP.put("cg4    ".trim(), "application/x-g4                              ".trim());
        MIME_MAP.put("cgm    ".trim(), "application/x-cgm                   ".trim());
        MIME_MAP.put("cit    ".trim(), "application/x-cit                          ".trim());
        MIME_MAP.put("class".trim(), "java/*                              ".trim());
        MIME_MAP.put("cml    ".trim(), "text/xml                                      ".trim());
        MIME_MAP.put("cmp    ".trim(), "application/x-cmp                   ".trim());
        MIME_MAP.put("cmx    ".trim(), "application/x-cmx                          ".trim());
        MIME_MAP.put("cot    ".trim(), "application/x-cot                   ".trim());
        MIME_MAP.put("crl    ".trim(), "application/pkix-crl                          ".trim());
        MIME_MAP.put("crt    ".trim(), "application/x-x509-ca-cert          ".trim());
        MIME_MAP.put("csi    ".trim(), "application/x-csi                          ".trim());
        MIME_MAP.put("css    ".trim(), "text/css                            ".trim());
        MIME_MAP.put("cut    ".trim(), "application/x-cut                          ".trim());
        MIME_MAP.put("dbf    ".trim(), "application/x-dbf                   ".trim());
        MIME_MAP.put("dbm    ".trim(), "application/x-dbm                          ".trim());
        MIME_MAP.put("dbx    ".trim(), "application/x-dbx                   ".trim());
        MIME_MAP.put("dcd    ".trim(), "text/xml                                      ".trim());
        MIME_MAP.put("dcx    ".trim(), "application/x-dcx                   ".trim());
        MIME_MAP.put("der    ".trim(), "application/x-x509-ca-cert                  ".trim());
        MIME_MAP.put("dgn    ".trim(), "application/x-dgn                   ".trim());
        MIME_MAP.put("dib    ".trim(), "application/x-dib                          ".trim());
        MIME_MAP.put("dll    ".trim(), "application/x-msdownload            ".trim());
        MIME_MAP.put("doc    ".trim(), "application/msword                          ".trim());
        MIME_MAP.put("dot    ".trim(), "application/msword                  ".trim());
        MIME_MAP.put("drw    ".trim(), "application/x-drw                          ".trim());
        MIME_MAP.put("dtd    ".trim(), "text/xml                            ".trim());
        MIME_MAP.put("dwf    ".trim(), "Model/vnd.dwf                              ".trim());
        MIME_MAP.put("dwf    ".trim(), "application/x-dwf                   ".trim());
        MIME_MAP.put("dwg    ".trim(), "application/x-dwg                          ".trim());
        MIME_MAP.put("dxb    ".trim(), "application/x-dxb                   ".trim());
        MIME_MAP.put("dxf    ".trim(), "application/x-dxf                          ".trim());
        MIME_MAP.put("edn    ".trim(), "application/vnd.adobe.edn           ".trim());
        MIME_MAP.put("emf    ".trim(), "application/x-emf                          ".trim());
        MIME_MAP.put("eml    ".trim(), "message/rfc822                      ".trim());
        MIME_MAP.put("ent    ".trim(), "text/xml                                      ".trim());
        MIME_MAP.put("epi    ".trim(), "application/x-epi                   ".trim());
        MIME_MAP.put("eps    ".trim(), "application/x-ps                              ".trim());
        MIME_MAP.put("eps    ".trim(), "application/postscript              ".trim());
        MIME_MAP.put("etd    ".trim(), "application/x-ebx                          ".trim());
        MIME_MAP.put("exe    ".trim(), "application/x-msdownload            ".trim());
        MIME_MAP.put("fax    ".trim(), "image/fax                                  ".trim());
        MIME_MAP.put("fdf    ".trim(), "application/vnd.fdf                 ".trim());
        MIME_MAP.put("fif    ".trim(), "application/fractals                          ".trim());
        MIME_MAP.put("fo    ".trim(), "text/xml                            ".trim());
        MIME_MAP.put("frm    ".trim(), "application/x-frm                          ".trim());
        MIME_MAP.put("g4    ".trim(), "application/x-g4                    ".trim());
        MIME_MAP.put("gbr    ".trim(), "application/x-gbr                          ".trim());
        MIME_MAP.put("gif    ".trim(), "image/gif                                  ".trim());
        MIME_MAP.put("gl2    ".trim(), "application/x-gl2                   ".trim());
        MIME_MAP.put("gp4    ".trim(), "application/x-gp4                          ".trim());
        MIME_MAP.put("hgl    ".trim(), "application/x-hgl                   ".trim());
        MIME_MAP.put("hmr    ".trim(), "application/x-hmr                          ".trim());
        MIME_MAP.put("hpg    ".trim(), "application/x-hpgl                  ".trim());
        MIME_MAP.put("hpl    ".trim(), "application/x-hpl                          ".trim());
        MIME_MAP.put("hqx    ".trim(), "application/mac-binhex40            ".trim());
        MIME_MAP.put("hrf    ".trim(), "application/x-hrf                          ".trim());
        MIME_MAP.put("hta    ".trim(), "application/hta                     ".trim());
        MIME_MAP.put("htc    ".trim(), "text/x-component                              ".trim());
        MIME_MAP.put("htm    ".trim(), "text/html                           ".trim());
        MIME_MAP.put("html    ".trim(), "text/html                                  ".trim());
        MIME_MAP.put("htt    ".trim(), "text/webviewhtml                    ".trim());
        MIME_MAP.put("htx    ".trim(), "text/html                                  ".trim());
        MIME_MAP.put("icb    ".trim(), "application/x-icb                   ".trim());
        MIME_MAP.put("ico    ".trim(), "image/x-icon                                  ".trim());
        MIME_MAP.put("ico    ".trim(), "application/x-ico                   ".trim());
        MIME_MAP.put("iff    ".trim(), "application/x-iff                          ".trim());
        MIME_MAP.put("ig4    ".trim(), "application/x-g4                    ".trim());
        MIME_MAP.put("igs    ".trim(), "application/x-igs                          ".trim());
        MIME_MAP.put("iii    ".trim(), "application/x-iphone                ".trim());
        MIME_MAP.put("img    ".trim(), "application/x-img                          ".trim());
        MIME_MAP.put("ins    ".trim(), "application/x-internet-signup       ".trim());
        MIME_MAP.put("isp    ".trim(), "application/x-internet-signup              ".trim());
        MIME_MAP.put("IVF    ".trim(), "video/x-ivf                         ".trim());
        MIME_MAP.put("java    ".trim(), "java/*                                      ".trim());
        MIME_MAP.put("jfif".trim(), "image/jpeg                          ".trim());
        MIME_MAP.put("jpe    ".trim(), "image/jpeg                                  ".trim());
        MIME_MAP.put("jpe    ".trim(), "application/x-jpe                   ".trim());
        MIME_MAP.put("jpeg    ".trim(), "image/jpeg                                  ".trim());
        MIME_MAP.put("jpg    ".trim(), "image/jpeg                          ".trim());
        MIME_MAP.put("jpg    ".trim(), "application/x-jpg                          ".trim());
        MIME_MAP.put("js    ".trim(), "application/x-javascript            ".trim());
        MIME_MAP.put("jsp    ".trim(), "text/html                                  ".trim());
        MIME_MAP.put("la1    ".trim(), "audio/x-liquid-file                 ".trim());
        MIME_MAP.put("lar    ".trim(), "application/x-laplayer-reg                  ".trim());
        MIME_MAP.put("latex".trim(), "application/x-latex                 ".trim());
        MIME_MAP.put("lavs    ".trim(), "audio/x-liquid-secure                      ".trim());
        MIME_MAP.put("lbm    ".trim(), "application/x-lbm                   ".trim());
        MIME_MAP.put("lmsff    ".trim(), "audio/x-la-lms                              ".trim());
        MIME_MAP.put("ls    ".trim(), "application/x-javascript            ".trim());
        MIME_MAP.put("ltr    ".trim(), "application/x-ltr                          ".trim());
        MIME_MAP.put("m1v    ".trim(), "video/x-mpeg                        ".trim());
        MIME_MAP.put("m2v    ".trim(), "video/x-mpeg                                  ".trim());
        MIME_MAP.put("m3u    ".trim(), "audio/mpegurl                       ".trim());
        MIME_MAP.put("m4e    ".trim(), "video/mpeg4                                  ".trim());
        MIME_MAP.put("mac    ".trim(), "application/x-mac                   ".trim());
        MIME_MAP.put("man    ".trim(), "application/x-troff-man                      ".trim());
        MIME_MAP.put("math".trim(), "text/xml                            ".trim());
        MIME_MAP.put("mdb    ".trim(), "application/msaccess                          ".trim());
        MIME_MAP.put("mdb    ".trim(), "application/x-mdb                   ".trim());
        MIME_MAP.put("mfp    ".trim(), "application/x-shockwave-flash              ".trim());
        MIME_MAP.put("mht    ".trim(), "message/rfc822                      ".trim());
        MIME_MAP.put("mhtml    ".trim(), "message/rfc822                              ".trim());
        MIME_MAP.put("mi    ".trim(), "application/x-mi                    ".trim());
        MIME_MAP.put("mid    ".trim(), "audio/mid                                  ".trim());
        MIME_MAP.put("midi".trim(), "audio/mid                           ".trim());
        MIME_MAP.put("mil    ".trim(), "application/x-mil                          ".trim());
        MIME_MAP.put("mml    ".trim(), "text/xml                            ".trim());
        MIME_MAP.put("mnd    ".trim(), "audio/x-musicnet-download                  ".trim());
        MIME_MAP.put("mns    ".trim(), "audio/x-musicnet-stream             ".trim());
        MIME_MAP.put("mocha    ".trim(), "application/x-javascript                      ".trim());
        MIME_MAP.put("movie".trim(), "video/x-sgi-movie                   ".trim());
        MIME_MAP.put("mp1    ".trim(), "audio/mp1                                  ".trim());
        MIME_MAP.put("mp2    ".trim(), "audio/mp2                           ".trim());
        MIME_MAP.put("mp2v    ".trim(), "video/mpeg                                  ".trim());
        MIME_MAP.put("mp3    ".trim(), "audio/mp3                           ".trim());
        MIME_MAP.put("mp4    ".trim(), "video/mpeg4                                  ".trim());
        MIME_MAP.put("mpa    ".trim(), "video/x-mpg                         ".trim());
        MIME_MAP.put("mpd    ".trim(), "application/vnd.ms-project                  ".trim());
        MIME_MAP.put("mpe    ".trim(), "video/x-mpeg                        ".trim());
        MIME_MAP.put("mpeg    ".trim(), "video/mpg                                  ".trim());
        MIME_MAP.put("mpg    ".trim(), "video/mpg                           ".trim());
        MIME_MAP.put("mpga    ".trim(), "audio/rn-mpeg                              ".trim());
        MIME_MAP.put("mpp    ".trim(), "application/vnd.ms-project          ".trim());
        MIME_MAP.put("mps    ".trim(), "video/x-mpeg                                  ".trim());
        MIME_MAP.put("mpt    ".trim(), "application/vnd.ms-project          ".trim());
        MIME_MAP.put("mpv    ".trim(), "video/mpg                                  ".trim());
        MIME_MAP.put("mpv2".trim(), "video/mpeg                          ".trim());
        MIME_MAP.put("mpw    ".trim(), "application/vnd.ms-project                  ".trim());
        MIME_MAP.put("mpx    ".trim(), "application/vnd.ms-project          ".trim());
        MIME_MAP.put("mtx    ".trim(), "text/xml                                      ".trim());
        MIME_MAP.put("mxp    ".trim(), "application/x-mmxp                  ".trim());
        MIME_MAP.put("net    ".trim(), "image/pnetvue                              ".trim());
        MIME_MAP.put("nrf    ".trim(), "application/x-nrf                   ".trim());
        MIME_MAP.put("nws    ".trim(), "message/rfc822                              ".trim());
        MIME_MAP.put("odc    ".trim(), "text/x-ms-odc                       ".trim());
        MIME_MAP.put("out    ".trim(), "application/x-out                          ".trim());
        MIME_MAP.put("p10    ".trim(), "application/pkcs10                  ".trim());
        MIME_MAP.put("p12    ".trim(), "application/x-pkcs12                          ".trim());
        MIME_MAP.put("p7b    ".trim(), "application/x-pkcs7-certificates    ".trim());
        MIME_MAP.put("p7c    ".trim(), "application/pkcs7-mime                      ".trim());
        MIME_MAP.put("p7m    ".trim(), "application/pkcs7-mime              ".trim());
        MIME_MAP.put("p7r    ".trim(), "application/x-pkcs7-certreqresp              ".trim());
        MIME_MAP.put("p7s    ".trim(), "application/pkcs7-signature         ".trim());
        MIME_MAP.put("pc5    ".trim(), "application/x-pc5                          ".trim());
        MIME_MAP.put("pci    ".trim(), "application/x-pci                   ".trim());
        MIME_MAP.put("pcl    ".trim(), "application/x-pcl                          ".trim());
        MIME_MAP.put("pcx    ".trim(), "application/x-pcx                   ".trim());
        MIME_MAP.put("pdf    ".trim(), "application/pdf                              ".trim());
        MIME_MAP.put("tif    ".trim(), "image/tiff                          ".trim());
        MIME_MAP.put("pdx    ".trim(), "application/vnd.adobe.pdx                  ".trim());
        MIME_MAP.put("pfx    ".trim(), "application/x-pkcs12                ".trim());
        MIME_MAP.put("pgl    ".trim(), "application/x-pgl                          ".trim());
        MIME_MAP.put("pic    ".trim(), "application/x-pic                   ".trim());
        MIME_MAP.put("pko    ".trim(), "application/vnd.ms-pki.pko                  ".trim());
        MIME_MAP.put("pl    ".trim(), "application/x-perl                  ".trim());
        MIME_MAP.put("plg    ".trim(), "text/html                                  ".trim());
        MIME_MAP.put("pls    ".trim(), "audio/scpls                         ".trim());
        MIME_MAP.put("plt    ".trim(), "application/x-plt                          ".trim());
        MIME_MAP.put("png    ".trim(), "image/png                           ".trim());
        MIME_MAP.put("png    ".trim(), "application/x-png                          ".trim());
        MIME_MAP.put("pot    ".trim(), "application/vnd.ms-powerpoint       ".trim());
        MIME_MAP.put("ppa    ".trim(), "application/vnd.ms-powerpoint              ".trim());
        MIME_MAP.put("ppm    ".trim(), "application/x-ppm                   ".trim());
        MIME_MAP.put("pps    ".trim(), "application/vnd.ms-powerpoint              ".trim());
        MIME_MAP.put("ppt    ".trim(), "application/vnd.ms-powerpoint       ".trim());
        MIME_MAP.put("ppt    ".trim(), "application/x-ppt                          ".trim());
        MIME_MAP.put("pr    ".trim(), "application/x-pr                    ".trim());
        MIME_MAP.put("prf    ".trim(), "application/pics-rules                      ".trim());
        MIME_MAP.put("prn    ".trim(), "application/x-prn                   ".trim());
        MIME_MAP.put("prt    ".trim(), "application/x-prt                          ".trim());
        MIME_MAP.put("ps  ".trim(), "application/x-ps                     ".trim());
        MIME_MAP.put("ps        ".trim(), "application/postscript                      ".trim());
        MIME_MAP.put("ptn    ".trim(), "application/x-ptn                   ".trim());
        MIME_MAP.put("pwz    ".trim(), "application/vnd.ms-powerpoint              ".trim());
        MIME_MAP.put("r3t    ".trim(), "text/vnd.rn-realtext3d              ".trim());
        MIME_MAP.put("ra        ".trim(), "audio/vnd.rn-realaudio                      ".trim());
        MIME_MAP.put("ram    ".trim(), "audio/x-pn-realaudio                ".trim());
        MIME_MAP.put("ras    ".trim(), "application/x-ras                          ".trim());
        MIME_MAP.put("rat    ".trim(), "application/rat-file                ".trim());
        MIME_MAP.put("rdf    ".trim(), "text/xml                                      ".trim());
        MIME_MAP.put("rec    ".trim(), "application/vnd.rn-recording        ".trim());
        MIME_MAP.put("red    ".trim(), "application/x-red                          ".trim());
        MIME_MAP.put("rgb    ".trim(), "application/x-rgb                   ".trim());
        MIME_MAP.put("rjs    ".trim(), "application/vnd.rn-realsystem-rjs          ".trim());
        MIME_MAP.put("rjt    ".trim(), "application/vnd.rn-realsystem-rjt   ".trim());
        MIME_MAP.put("rlc    ".trim(), "application/x-rlc                          ".trim());
        MIME_MAP.put("rle    ".trim(), "application/x-rle                   ".trim());
        MIME_MAP.put("rm        ".trim(), "application/vnd.rn-realmedia                  ".trim());
        MIME_MAP.put("rmf    ".trim(), "application/vnd.adobe.rmf           ".trim());
        MIME_MAP.put("rmi    ".trim(), "audio/mid                                  ".trim());
        MIME_MAP.put("rmj    ".trim(), "application/vnd.rn-realsystem-rmj   ".trim());
        MIME_MAP.put("rmm    ".trim(), "audio/x-pn-realaudio                          ".trim());
        MIME_MAP.put("rmp    ".trim(), "application/vnd.rn-rn_music_package ".trim());
        MIME_MAP.put("rms    ".trim(), "application/vnd.rn-realmedia-secure          ".trim());
        MIME_MAP.put("rmvb".trim(), "application/vnd.rn-realmedia-vbr    ".trim());
        MIME_MAP.put("rmx    ".trim(), "application/vnd.rn-realsystem-rmx          ".trim());
        MIME_MAP.put("rnx    ".trim(), "application/vnd.rn-realplayer       ".trim());
        MIME_MAP.put("rp        ".trim(), "image/vnd.rn-realpix                          ".trim());
        MIME_MAP.put("rpm    ".trim(), "audio/x-pn-realaudio-plugin         ".trim());
        MIME_MAP.put("rsml    ".trim(), "application/vnd.rn-rsml                      ".trim());
        MIME_MAP.put("rt    ".trim(), "text/vnd.rn-realtext                ".trim());
        MIME_MAP.put("rtf    ".trim(), "application/msword                          ".trim());
        MIME_MAP.put("rtf    ".trim(), "application/x-rtf                   ".trim());
        MIME_MAP.put("rv        ".trim(), "video/vnd.rn-realvideo                      ".trim());
        MIME_MAP.put("sam    ".trim(), "application/x-sam                   ".trim());
        MIME_MAP.put("sat    ".trim(), "application/x-sat                          ".trim());
        MIME_MAP.put("sdp    ".trim(), "application/sdp                     ".trim());
        MIME_MAP.put("sdw    ".trim(), "application/x-sdw                          ".trim());
        MIME_MAP.put("sit    ".trim(), "application/x-stuffit               ".trim());
        MIME_MAP.put("slb    ".trim(), "application/x-slb                          ".trim());
        MIME_MAP.put("sld    ".trim(), "application/x-sld                   ".trim());
        MIME_MAP.put("slk    ".trim(), "drawing/x-slk                              ".trim());
        MIME_MAP.put("smi    ".trim(), "application/smil                    ".trim());
        MIME_MAP.put("smil    ".trim(), "application/smil                              ".trim());
        MIME_MAP.put("smk    ".trim(), "application/x-smk                   ".trim());
        MIME_MAP.put("snd    ".trim(), "audio/basic                                  ".trim());
        MIME_MAP.put("sol    ".trim(), "text/plain                          ".trim());
        MIME_MAP.put("sor    ".trim(), "text/plain                                  ".trim());
        MIME_MAP.put("spc    ".trim(), "application/x-pkcs7-certificates    ".trim());
        MIME_MAP.put("spl    ".trim(), "application/futuresplash                      ".trim());
        MIME_MAP.put("spp    ".trim(), "text/xml                            ".trim());
        MIME_MAP.put("ssm    ".trim(), "application/streamingmedia                  ".trim());
        MIME_MAP.put("sst    ".trim(), "application/vnd.ms-pki.certstore    ".trim());
        MIME_MAP.put("stl    ".trim(), "application/vnd.ms-pki.stl                  ".trim());
        MIME_MAP.put("stm    ".trim(), "text/html                           ".trim());
        MIME_MAP.put("sty    ".trim(), "application/x-sty                          ".trim());
        MIME_MAP.put("svg    ".trim(), "text/xml                            ".trim());
        MIME_MAP.put("swf    ".trim(), "application/x-shockwave-flash              ".trim());
        MIME_MAP.put("tdf    ".trim(), "application/x-tdf                   ".trim());
        MIME_MAP.put("tg4    ".trim(), "application/x-tg4                          ".trim());
        MIME_MAP.put("tga    ".trim(), "application/x-tga                   ".trim());
        MIME_MAP.put("tif    ".trim(), "image/tiff                                  ".trim());
        MIME_MAP.put("tif    ".trim(), "application/x-tif                   ".trim());
        MIME_MAP.put("tiff    ".trim(), "image/tiff                                  ".trim());
        MIME_MAP.put("tld    ".trim(), "text/xml                            ".trim());
        MIME_MAP.put("top    ".trim(), "drawing/x-top                              ".trim());
        MIME_MAP.put("torrent".trim(), "application/x-bittorrent            ".trim());
        MIME_MAP.put("tsd    ".trim(), "text/xml                                      ".trim());
        MIME_MAP.put("txt    ".trim(), "text/plain                          ".trim());
        MIME_MAP.put("uin    ".trim(), "application/x-icq                          ".trim());
        MIME_MAP.put("uls    ".trim(), "text/iuls                           ".trim());
        MIME_MAP.put("vcf    ".trim(), "text/x-vcard                                  ".trim());
        MIME_MAP.put("vda    ".trim(), "application/x-vda                   ".trim());
        MIME_MAP.put("vdx    ".trim(), "application/vnd.visio                      ".trim());
        MIME_MAP.put("vml    ".trim(), "text/xml                            ".trim());
        MIME_MAP.put("vpg    ".trim(), "application/x-vpeg005                      ".trim());
        MIME_MAP.put("vsd    ".trim(), "application/vnd.visio               ".trim());
        MIME_MAP.put("vsd    ".trim(), "application/x-vsd                          ".trim());
        MIME_MAP.put("vss    ".trim(), "application/vnd.visio               ".trim());
        MIME_MAP.put("vst    ".trim(), "application/vnd.visio                      ".trim());
        MIME_MAP.put("vst    ".trim(), "application/x-vst                   ".trim());
        MIME_MAP.put("vsw    ".trim(), "application/vnd.visio                      ".trim());
        MIME_MAP.put("vsx    ".trim(), "application/vnd.visio               ".trim());
        MIME_MAP.put("vtx    ".trim(), "application/vnd.visio                      ".trim());
        MIME_MAP.put("vxml".trim(), "text/xml                            ".trim());
        MIME_MAP.put("wav    ".trim(), "audio/wav                                  ".trim());
        MIME_MAP.put("wax    ".trim(), "audio/x-ms-wax                      ".trim());
        MIME_MAP.put("wb1    ".trim(), "application/x-wb1                          ".trim());
        MIME_MAP.put("wb2    ".trim(), "application/x-wb2                   ".trim());
        MIME_MAP.put("wb3    ".trim(), "application/x-wb3                          ".trim());
        MIME_MAP.put("wbmp".trim(), "image/vnd.wap.wbmp                  ".trim());
        MIME_MAP.put("wiz    ".trim(), "application/msword                          ".trim());
        MIME_MAP.put("wk3    ".trim(), "application/x-wk3                   ".trim());
        MIME_MAP.put("wk4    ".trim(), "application/x-wk4                          ".trim());
        MIME_MAP.put("wkq    ".trim(), "application/x-wkq                   ".trim());
        MIME_MAP.put("wks    ".trim(), "application/x-wks                          ".trim());
        MIME_MAP.put("wm    ".trim(), "video/x-ms-wm                       ".trim());
        MIME_MAP.put("wma    ".trim(), "audio/x-ms-wma                              ".trim());
        MIME_MAP.put("wmd    ".trim(), "application/x-ms-wmd                ".trim());
        MIME_MAP.put("wmf    ".trim(), "application/x-wmf                          ".trim());
        MIME_MAP.put("wml    ".trim(), "text/vnd.wap.wml                    ".trim());
        MIME_MAP.put("wmv    ".trim(), "video/x-ms-wmv                              ".trim());
        MIME_MAP.put("wmx    ".trim(), "video/x-ms-wmx                      ".trim());
        MIME_MAP.put("wmz    ".trim(), "application/x-ms-wmz                          ".trim());
        MIME_MAP.put("wp6    ".trim(), "application/x-wp6                   ".trim());
        MIME_MAP.put("wpd    ".trim(), "application/x-wpd                          ".trim());
        MIME_MAP.put("wpg    ".trim(), "application/x-wpg                   ".trim());
        MIME_MAP.put("wpl    ".trim(), "application/vnd.ms-wpl                      ".trim());
        MIME_MAP.put("wq1    ".trim(), "application/x-wq1                   ".trim());
        MIME_MAP.put("wr1    ".trim(), "application/x-wr1                          ".trim());
        MIME_MAP.put("wri    ".trim(), "application/x-wri                   ".trim());
        MIME_MAP.put("wrk    ".trim(), "application/x-wrk                          ".trim());
        MIME_MAP.put("ws    ".trim(), "application/x-ws                    ".trim());
        MIME_MAP.put("ws2    ".trim(), "application/x-ws                              ".trim());
        MIME_MAP.put("wsc    ".trim(), "text/scriptlet                      ".trim());
        MIME_MAP.put("wsdl    ".trim(), "text/xml                                      ".trim());
        MIME_MAP.put("wvx    ".trim(), "video/x-ms-wvx                      ".trim());
        MIME_MAP.put("xdp    ".trim(), "application/vnd.adobe.xdp                  ".trim());
        MIME_MAP.put("xdr    ".trim(), "text/xml                            ".trim());
        MIME_MAP.put("xfd    ".trim(), "application/vnd.adobe.xfd                  ".trim());
        MIME_MAP.put("xfdf".trim(), "application/vnd.adobe.xfdf          ".trim());
        MIME_MAP.put("xhtml    ".trim(), "text/html                                  ".trim());
        MIME_MAP.put("xls    ".trim(), "application/vnd.ms-excel application/x-excel".trim());
        MIME_MAP.put("xlw    ".trim(), "application/x-xlw                   ".trim());
        MIME_MAP.put("xml    ".trim(), "text/xml                                      ".trim());
        MIME_MAP.put("xpl    ".trim(), "audio/scpls                         ".trim());
        MIME_MAP.put("xq        ".trim(), "text/xml                                      ".trim());
        MIME_MAP.put("xql    ".trim(), "text/xml                            ".trim());
        MIME_MAP.put("xquery    ".trim(), "text/xml                                      ".trim());
        MIME_MAP.put("xsd    ".trim(), "text/xml                            ".trim());
        MIME_MAP.put("xsl    ".trim(), "text/xml                                      ".trim());
        MIME_MAP.put("xslt".trim(), "text/xml                            ".trim());
        MIME_MAP.put("xwd    ".trim(), "application/x-xwd                          ".trim());
        MIME_MAP.put("x_b    ".trim(), "application/x-x_b                   ".trim());
        MIME_MAP.put("sis    ".trim(), "application/vnd.symbian.install              ".trim());
        MIME_MAP.put("sisx".trim(), "application/vnd.symbian.install     ".trim());
        MIME_MAP.put("x_t    ".trim(), "application/x-x_t                          ".trim());
        MIME_MAP.put("ipa    ".trim(), "application/vnd.iphone              ".trim());
        MIME_MAP.put("apk    ".trim(), "application/vnd.android.package-archive      ".trim());
        MIME_MAP.put("xap    ".trim(), "application/x-silverlight-app       ".trim());

        MIME_MAP.put(DEFAULT_FILE_TYPE, DEFAULT_MIME_TYPE);
    }

    /**
     * 根据文件后缀获取Mime类型
     *
     * @param docSuffix 文档后缀
     * @return          Mime类型
     */
    public static final String getMimeType(String docSuffix) {
        String mime = MIME_MAP.get(docSuffix);
        if (null == mime) {
            return DEFAULT_MIME_TYPE;
        }
        return mime;
    }
}
